{{- if .Values.juiceShopCleanup.enabled -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: 'cleanup-job'
  labels:
    {{- include "multi-juicer.cleaner.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.juiceShopCleanup.cron }}
  successfulJobsHistoryLimit: {{ .Values.juiceShopCleanup.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.juiceShopCleanup.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "multi-juicer.cleaner.labels" . | nindent 12 }}
        spec:
          serviceAccountName: 'juice-cleaner'
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          {{- with .Values.juiceShopCleanup.podSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          containers:
            - image: '{{ .Values.juiceShopCleanup.repository }}:{{ .Values.juiceShopCleanup.tag | default (printf "v%s" .Chart.Version) }}'
              imagePullPolicy: {{ .Values.imagePullPolicy | quote }}
              name: 'cleanup-job'
              {{- with .Values.juiceShopCleanup.containerSecurityContext }}
              securityContext:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              env:
                - name: NAMESPACE
                  value: {{ .Release.Namespace | quote }}
                - name: MAX_INACTIVE_DURATION
                  value: {{ .Values.juiceShopCleanup.gracePeriod }}
          restartPolicy: Never
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.juiceShopCleanup.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.juiceShopCleanup.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}
