name: release
on:
  push:
    tags:
      - 'v*'

jobs:
  tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Create tag
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.updateRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'tags/latest',
              sha: context.sha
            })
          

#  release:
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        component:
#          - progress-watchdog
#          - cleaner
#          - balancer
#    steps:
#      - uses: actions/checkout@v4
#      - uses: docker/setup-qemu-action@v3
#      - uses: docker/setup-buildx-action@v3
#      - uses: digitalocean/action-doctl@v2
#        with:
#          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
#
#      - id: tag
#        run: |
#          echo "SOURCE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
#
#      - run: doctl registry login --expiry-seconds 3600
#
#      - uses: docker/build-push-action@v6
#        with:
#          context: ./${{ matrix.component }}
#          file: ./${{ matrix.component }}/Dockerfile
#          platforms: linux/amd64
#          push: true
#          tags: |
#            registry.digitalocean.com/scyon/multi-juicer/${{ matrix.component }}:${{ env.SOURCE_TAG }}
#            registry.digitalocean.com/scyon/multi-juicer/${{ matrix.component }}:latest
#          build-args: |
#            VCS_REF=$(git rev-parse --short HEAD)
#            BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

